remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "How Much to Offer? A Practical Guide to Sizing Innovation Incentives"
description: "A framework estimating the appropriate size of an advance market commitment"
menu:
  - name: "Home"
    link: "/"
  - name: "Simple Sizing Graph"
    link: "/simple_sizing_graph.html"
  - name: "Needed Firm Entry"
    link: "/needed_firm_entry_graph.html"
  - name: "Complete Sizing Graph"
    link: "/complete_sizing_graph.html"
